create table patients (
id bigint generated by default as identity (start with 1, increment by 1) not null primary key,
name varchar(50) not null,
surname varchar(128) not null,
patronymic varchar(50),
phone varchar(30))

create table doctors (
id bigint generated by default as identity (start with 1, increment by 1) not null primary key,
name varchar(50) not null,
surname varchar(128) not null,
patronymic varchar(50),
specialization varchar(128))

create table recepies (
id bigint generated by default as identity (start with 1, increment by 1) not null primary key,
description varchar(256) not null,
patientId bigint not null,
doctorId bigint not null,
creationDate date default CURRENT_DATE not null,
validityLength tinyint default 7 not null,
priority varchar(50) default 'Нормальный' not null,  -- 'Нормальный', 'Cito (Срочный)', 'Statim (Немедленный)'
foreign key (patientId) references patients(id),
foreign key (doctorId) references doctors(id))

